### ISSUE TITLE
Grid representation

### ISSUE THREAD

**Issue by charleskawczynski** [SciML/DiffEqOperators.jl#214] opened 2019-12-24 02:47 UTC
What’s the vision for DiffEqOperators.jl in terms of a grid/mesh representation? 

It’s an important component, and right now it seems very lightweight.

cc @ChrisRackauckas

**Comment by ChrisRackauckas** [comment] 2019-12-24 08:50
I think we just need to make a lazy representation, where we take in AbstractVector and then can do `X[i,j]` from them in fast ways. That would make a 2D range essentially when made from two ranges, but then would allow for representing the 3D grid in O(n) memory. Just haven't made it yet.

**Comment by charleskawczynski** [comment] 2020-01-05 21:28
Ok, that's fair. Is there a built-in assumption with using 2D ranges? For example, `dx` is only a function of `x`, `dy` is only a function of `y`, etc?

Also, will this representation support non-uniform grids?

**Comment by ChrisRackauckas** [comment] 2020-01-06 13:04
Note that I mentioned it should be based on `AbstractVector`, which would make it allow ranges and vectors, and that would make it compatible. Basically it's mostly about making `X[i,j]` backed by two AbstractVectors, instead of storing the matrix, making it save memory by being a sparser format than `meshgrid`

**Comment by ChrisRackauckas** [comment] 2021-03-28 11:25
Duplicate of https://github.com/SciML/DiffEqOperators.jl/issues/22

**Closed by ChrisRackauckas** 2021-03-28 11:25 UTC
Labels: duplicate
